### ISSUE TITLE
Finalize RM1 Support

### ISSUE THREAD

**Issue by isaacwisdom** [isaacwisdom/RemarkableLamyEraser#12]
RM1 code is working, although somewhat buggy. To finish implementation, I need someone with an RM1 to grab the screen locations for the buttons on the RM1. I've written a program that will do this, and I have a pdf that will show you where to press. leave a comment if this is something you're interested in helping out with

**Comment by jack-margeson** [comment]
Hi- I'm new to reMarkable hacking (working off RM1 with stock launcher currently) but would love to see support for the RM1, let me know how I could help!

**Comment by isaacwisdom** [comment]
Awesome! So I’ll need you to load a pdf onto your RM with a marked locations for you to press, and then have you run a program I’ve written that will record locations. Once the program is finished it’ll spit out the information it gathered, and you can post that back here.
You’ll have to do it twice, the first time with your finger, and the second time with your pen. Once I get the screen locations loaded into the code, RM1 support should be finalized!

I’ll post the install instructions at the link below sometime tonight, I’ll make a comment here once it’s ready. 
https://github.com/isaacwisdom/RemarkableGetScreenLocations

**Comment by isaacwisdom** [comment]
Instructions are up!

**Comment by jack-margeson** [comment]
Great! Not quite sure which /dev/input/ events correspond to the RM1, as I ended up using event0 for the pen as stated in the instructions while event1 actually didn't output anything--but using event2 allowed me to get the touchscreen inputs. Attached are two text files with the coordinates that the script spit out. Hope this helps--let me know if there's anything else!

[locations_rm1_pen.txt](https://github.com/isaacwisdom/RemarkableLamyEraser/files/6851219/locations_rm1_pen.txt)
[locations_rm1_touchscreen.txt](https://github.com/isaacwisdom/RemarkableLamyEraser/files/6851220/locations_rm1_touchscreen.txt)

**Comment by Eeems** [comment]
Just a warning, it looks like input locations are getting changed in 2.9 for the rM1. You might want to add logic to just dynamically determine what input to use.

https://github.com/rmkit-dev/rmkit/blob/a99b2f70c72539bedc1d201e3899da6e19c197da/src/rmkit/input/device_id.cpy#L37

**Comment by bordaigorl** [comment]
Any update on making this work on RM1?

**Comment by isaacwisdom** [comment]
Unfortunately, since I don't have an RM1 to test with I haven't been able to really make any progress on this front other than some janky workarounds to make the RM2 seem like an RM1. Fundamentally, the way that my project is implemented just doesn't translate well to the RM1. 

However, there should be compatibility in the V2 branch. You can try installing that, and if doesn't run well, you can always uninstall.

**Comment by bordaigorl** [comment]
Thanks for the help!
I tried installing v2, but I get unreliable interactions.
I am using the default configuration, but the eraser gets triggered only randomly (I need to click/click&hold many times before it is picked up) and when it picks it up the eraser tool is selected (sometimes the eraser menu gets opened) and when I release the button the writing tool is not re-selected.
I could not trigger any other action.
If there's anything I can do to help let me know.

**Comment by isaacwisdom** [comment]
Hey! Thanks for the data. RM1 support has been added in the V2 branch, but from my testing it doesn't seem super reliable. If you'd like, you can install from that branch and give it a try.

**Comment by arturbecker** [comment]
I tried it from V2  on my RM1 today and had the following behavior:

- The toolbar has to be open for anything to happen (I don't know if this is intentional/necessary)
- With toolbar open, pressing and holding activates the eraser; releasing don't deactivate it
  - Tried with click trigger for eraser as well and clicking activates the eraser, but clicking again doesn't go back to writing tool

**Comment by pmeng** [comment]
I tried v2 with RM1 today as well, I totally agree on the findings of @arturbecker 

i did not change anything in the configuration

If I can help with testing, I am willing to do so :-)
Thanks for your work so far!

**Comment by isaacwisdom** [comment]
@arturbecker and @pmeng, Could you confirm for me what type of document you have open when seeing this behavior (ie, pdf or notebook) and also which software update you are on?

**Comment by arturbecker** [comment]
Notebook, software version 3.0.4.1305

**Comment by alioth9** [comment]
Thanks for the work @isaacwisdom
But with rM1 and SW v3.3 I can't use RemarkableLamyEraser the tools/actions or off. I don't know how you use the test data but since you test with a pdf It didn't take into account the difference with the Notebook. In particular there is the new Text tools.
If I can help .
It would be great to support v3.+ since ddvk stylus hacks can't work with v3.+

**Comment by chabad360** [comment]
I'm on v3.5.2 and the tool doesn't seem to work at all.
