### ISSUE TITLE
Not an issue, just a comment

### ISSUE THREAD

**Issue by deanhuff** [isaacwisdom/RemarkableLamyEraser#15]
I've applied this to my rm2 running 2.9.1.217  I can report that it works with Wacom One Pen CP91300B2Z.

Please feel free to close this issue.

**Comment by sterlingbaldwin** [comment]
Also not an issue, just a comment to say this project is amazing! So glad you put the work in to make this!

**Comment by isaacwisdom** [comment]
Thanks! I will update the readme.

**Comment by ctankep23** [comment]
I’m so happy you are working on this standalone tool and I’m following it closely. I haven’t installed yet because I only use the selection eraser, so I’m waiting for that, speaking of - how’s the testing on selection eraser function going? 

/Seb

**Comment by sterlingbaldwin** [comment]
@ctankep23 I think thats supported in (the as yet unreleased) v2, from poking around a little it looks like theres a whole bunch of options of what you can trigger with the side button.
