### ISSUE TITLE
v2-dev doesn't work with RM2 on ver. 2.9.1.217

### ISSUE THREAD

**Issue by naiqixiao** [isaacwisdom/RemarkableLamyEraser#16]
Thanks for your project! I like the way you implement customization in v2-dev branch. However, it doesn't work on my RM2 (2.9.1.217). Looking forward to the next update!

**Comment by Toorero** [comment]
It does work on my rm2 with my patch applied, perhaps you might want to check out #13.

**Comment by naiqixiao** [comment]
Thanks! It works now!
