### ISSUE TITLE
v2 branch doesn't install to 2.9.1.217

### ISSUE THREAD

**Issue by fbalobanov** [isaacwisdom/RemarkableLamyEraser#17]
Hi,

Thank you for the great tool.

I've tried to install v2 branch to 2.9.1.217 rm2, but it seems that something is wrong with the installation.

Answering 'y' to "Would you like to edit your configuration now? [y/n]" hangs SSH (I use putty) and if I answer 'no' service still doesn't work.

The stable version works fine without any issues.

**Comment by isaacwisdom** [comment]
Should work on the latest release now
