### ISSUE TITLE
v2-dev not working on rM2 Version 2.10.3.379

### ISSUE THREAD

**Issue by bsvh** [isaacwisdom/RemarkableLamyEraser#18]
I installed it and got it to run, and clicking and holding to erase works, but nothing else does. Selection eraser, undo, redo, selection, color-grey, and presumably all other options are not working. Running RemarkableLamyEraser from the terminal shows that the clicks are properly detected and the configuration file read. The correct effects are being written, but they aren't doing anyting.

Note, the undo click in version 1 is working.

**Comment by alvaroglm** [comment]
So itsn't working now?

**Comment by isaacwisdom** [comment]
Hi, It's been quite a while, but I have the v2 code working on the latest release and have been using it for a few days without issue. That being said, I've only gotten it working for selection, eraser, and undo). I have not gotten the others to work, and while I think I know why, it will probably be quite a while until I'm able to start developing this project again. Can you confirm that the v2 still doesn't work for you?
