### ISSUE TITLE
Double Press to undo

### ISSUE THREAD

**Issue by isaacwisdom** [isaacwisdom/RemarkableLamyEraser#2]
How this will be implemented:
1. Detect a double press of the button by watching the BTN_STYLUS events.
2. On a double press, write events that do this:
`Tap the screen where the undo button is`
`Tap the screen where the panel button is`
`Tap the screen where the undo button is`
`Tap the screen where the panel button is`

We do the commands in that specific order so that it doesn't matter if the tool panel is out, the undo button will be pressed exactly once and the panel will be returned to its starting state.

Writing the tap events should be easy, but some testing will be needed to see if pen events should be used at /dev/input/event1 or touchscreen events at /dev/input/event2.
In either case, I think something will have to be done to prevent any data being written while the above events are written. Otherwise, conflicting data about the location of the touch (most likely from your palm being on the screen) or the location of the pen (from the pen hovering over the screen) will get in the way of the above commands. 

Using ioctl and EVGIOC might help help that, but I think those are more for capturing the input generated by the kernel, and not for blocking the input events made by the kernel.

There is also the question of how quickly the above events can be written. The limiting factor will probably be how quickly the tool panel can open and close.

**Comment by isaacwisdom** [comment]
So some preliminary testing suggests that using the touch events will actually work without having to capture the event data. Since the reMarkable supports multitouch (up to 10 points I believe), you can send in another point fairly easily. It'll just get interpreted as another touch point without interrupting the other events, and from what I can tell so far, xochitl will still acknowledge a press on the undo button when other touch points are still active.

**Comment by Toorero** [comment]
That sounds great. Will this work regardless of the orientation or left-/righthand-mode?

**Comment by isaacwisdom** [comment]
> That sounds great. Will this work regardless of the orientation or left-/righthand-mode? 

Good point, I forgot about that. It'll just be a different location to press if the orientation is different. I'll make sure to add an argument to accommodate the left hand orientation

**Comment by isaacwisdom** [comment]
closed with release 1.1.0
