### ISSUE TITLE
Hold to change to selection tool

### ISSUE THREAD

**Issue by pragmatically-dev** [isaacwisdom/RemarkableLamyEraser#21]
Is there any way to send that event to toggle between tools?

**Comment by isaacwisdom** [comment]
In the v2 version that was just released, you should be able to configure the selection tool to behave how you want, wether as a toggle, or as a press&hold type effect. Reopen this issue if it isn't working for you!

**Comment by pragmatically-dev** [comment]
I'm getting some problems when I try to install the V2; wget return 404 not found 🤔 I'll try to install it by source but maybe it would be of help to let you know
