### ISSUE TITLE
Conflicting RM2 2.14.1.866

### ISSUE THREAD

**Issue by dawidadach** [isaacwisdom/RemarkableLamyEraser#25]
I've just installed that on my RM2 and I love it however... it seems to be breaking my gestures. 

After restart it works for some time but after couple of clicks with Lamy pen gesture stops working in any document (PDF/Notebook) . 

This is the only hack I installed so there is no other 3rd party software on my RM2

**Comment by isaacwisdom** [comment]
I just did some testing, and I see what you mean. There must've been a change in the way the touch data is handled at some point, as now it seems like my program is conflicting with the tablet. More investigation is needed, and I'll have to remove the v2 release :(

**Comment by pragmatically-dev** [comment]
I'll not Update my rm2 🤪 your tool is a life saver sir!!

**Comment by dawidadach** [comment]
> I just did some testing, and I see what you mean. There must've been a change in the way the touch data is handled at some point, as now it seems like my program is conflicting with the tablet. More investigation is needed, and I'll have to remove the v2 release :(

That's a pitty :( Your code is worth it's weight in gold <3 

Finger crossed for quick resolution

**Comment by pragmatically-dev** [comment]
V2 Branch works perfect on version 2.14.0.861

**Comment by dawidadach** [comment]
> V2 Branch works perfect on version 2.14.0.861

2.14.0.861 or 2.14.1.861 (the latest) ?

**Comment by pragmatically-dev** [comment]
For the first one, I didn't update my rm to the lastest

**Comment by matthiaskoerner-ba** [comment]
I tried and also found that neither the builtin cut-out-tool nor the eraser work anymore after reboots.

Actually, it seems to survive reboots when the LamyEraser.service is started **after xochitl**:
```
[Unit]
Description=Lamy Pen Button as Eraser
# After=home.mount
After=xochitl.service
[...]
```

With this, the builtin eraser tool and the cut tool still work after reboots.

@isaacwisdom Great work, thank you for your tool!

**Comment by isaacwisdom** [comment]
So, I did have problems on 2.14.1.xxx. However, I have been updated to v2.14.3.940, and gestures seem to be working. Anyone able to test on the latest version?
