### ISSUE TITLE
Install not working

### ISSUE THREAD

**Issue by SogehtTechnik** [isaacwisdom/RemarkableLamyEraser#29]
Hi,
I wanted to install your tool because I bought the Lamy pen. So I first SSH into the device and then (without making a folder) run the command from Github. There is nothing else in the description. Therefore, I assume that I am done. The problem is unfortunately that the eraser does not work. I also restarted the device and the button does not work. I am on Version 2.14.1.866

**Comment by isaacwisdom** [comment]
Have you previously installed the tool before? Additionally are you using RM1 or RM2?

**Comment by isaacwisdom** [comment]
Can you paste the output of the install script when you try to install?

**Comment by SogehtTechnik** [comment]
Downloading RemarkableLamyEraser Executable to /usr/sbin...
Connecting to github.com (140.82.121.4:443)
wget: note: TLS certificate validation not implemented
Connecting to raw.githubusercontent.com (185.199.109.133:443)
saving to 'RemarkableLamyEraser'
RemarkableLamyEraser 100% |********************************| 29636  0:00:00 ETA
'RemarkableLamyEraser' saved
Adding execute privleges...
Would you like RemarkableLamyEraser to start automatically on boot? [y/n]y
Downloading service file to /lib/systemd/system...
Connecting to github.com (140.82.121.4:443)
wget: note: TLS certificate validation not implemented
Connecting to raw.githubusercontent.com (185.199.108.133:443)
saving to 'LamyEraser.service'
LamyEraser.service   100% |********************************|   439  0:00:00 ETA
'LamyEraser.service' saved
Would you like to edit your configuration now? [y/n]n
Setting up RemarkableLamyEraser to start on boot...
Created symlink /etc/systemd/system/multi-user.target.wants/LamyEraser.service → /lib/systemd/system/LamyEraser.service.
Starting RemarkableLamyEraser. Enjoy!

**Comment by SogehtTechnik** [comment]
Is there something I have to do after installing? I did a reboot. Is there anything else?

**Comment by isaacwisdom** [comment]
Trying running directly from the command line.

RemarkableLamyEraser

**Comment by SogehtTechnik** [comment]
what do you mean with directly? I did it over ssh.

**Comment by SogehtTechnik** [comment]
RemarkableLamyEraser
RemarkableLamyEraser 1.2
No mode specified! Using default.
MODE: PRESS AND HOLD
No double click action specified! Using default.
DOUBLE CLICK ACTION: UNDO
Using Devices:
1. device file = /dev/input/event1
   device name = Wacom I2C Digitizer
2. device file = /dev/input/event2
   device name = pt_mt

**Comment by isaacwisdom** [comment]
Yes, ssh into the tablet, type "RemarkableLamyEraser" and press enter

**Comment by SogehtTechnik** [comment]
If I type **RemarkableLamyEraser** in the commandline the text above appears

**Comment by SogehtTechnik** [comment]
No fucking way. Now it works???

**Comment by SogehtTechnik** [comment]
I haven't done anything different?

**Comment by isaacwisdom** [comment]
It seems like there's probably a problem with it starting automatically after the install script, and then with it starting automatically on boot.
Can you run 

systemctl start LamyEraser.service

**Comment by SogehtTechnik** [comment]
I did but it isn't working

**Comment by isaacwisdom** [comment]
Please post the output of the command

**Comment by SogehtTechnik** [comment]
There is no output?

**Comment by isaacwisdom** [comment]
How about for

`systemctl stop LamyEraser.service
systemctl daemon-reload
systemctl start LamyEraser.service`

**Comment by SogehtTechnik** [comment]
<img width="566" alt="Bildschirmfoto 2022-08-10 um 21 41 46" src="https://user-images.githubusercontent.com/103176105/184005889-b822273d-8d16-46a5-9178-96f28c2cc082.png">

Nothing happens

**Comment by isaacwisdom** [comment]
That's really odd. Do you have any other hacks or modifications installed to your system?

Also try running

systemctl status

**Comment by SogehtTechnik** [comment]
No this is the only one.

**Comment by SogehtTechnik** [comment]
RemarkableLamyEraser 1.2
No mode specified! Using default.
             ├─systemd-logind.service 
             │ └─[[0;38;5;245m203 /lib/systemd/systemd-logind[[0m
             ├─system-busybox\x2difplugd.slice 
             │ └─busybox-ifplugd@usb0.service 
             │   └─[[0;38;5;245m207 /usr/sbin/ifplugd -n -i usb0[[0m
             ├─systemd-udevd.service 
             │ └─[[0;38;5;245m137 /lib/systemd/systemd-udevd[[0m
             ├─systemd-journald.service 
             │ └─[[0;38;5;245m136 /lib/systemd/systemd-journald[[0m
             ├─dhcpcd.service 
             │ └─[[0;38;5;245m219 /usr/sbin/dhcpcd -4 -b --master wlan0[[0
m
             ├─haveged.service 
             │ └─[[0;38;5;245m135 /usr/sbin/haveged -w 1024 -v 1 --Foregro
und[[0m
             ├─systemd-networkd.service 
             │ └─[[0;38;5;245m140 /lib/systemd/systemd-networkd[[0m
             ├─xochitl.service 
             │ └─[[0;38;5;245m231 /usr/bin/xochitl --system[[0m
             └─qmdns-responder.service 
               └─[[0;38;5;245m303 /usr/bin/qmdns-responder[[0m

**Comment by isaacwisdom** [comment]
Ok. So I'll suggest. 

cd

rm install.sh
rm uninstall.sh

Run the uninstall command, then reboot your remarkable, then try to reinstalll

**Comment by SogehtTechnik** [comment]
V2 or V1?

**Comment by isaacwisdom** [comment]
V1

**Comment by SogehtTechnik** [comment]
<img width="566" alt="Bildschirmfoto 2022-08-10 um 22 00 21" src="https://user-images.githubusercontent.com/103176105/184008998-0b1bfc8b-c3e3-44b8-a113-cb08617def6c.png">
It only works if I start the program manually

**Comment by WaylonWillie** [comment]
Just writing to report the same issue: New user, stock RM2, 2.14.1.866. Install does not work as above, but will work if manually started. Saw your note on another thread that it is working after the next update. Not looking to create work for you, so I'm happy to just wait for the update if it works there.

**Comment by dawidadach** [comment]
Same here on the newest beta 2.14.3.866 

`systemctl status LamyEraser.service
`
results: 


```
[[0;1;31m●[[0m LamyEraser.service - Lamy Pen Button as Eraser
     Loaded: loaded (/lib/systemd/system/LamyEraser.service; enabled; vendor preset: disabled)
     Active: [[0;1;31mfailed[[0m (Result: exit-code) since Thu 2022-08-11 08:13:43 UTC; 2s ago
    Process: 708 ExecStart=/home/root/RemarkableLamyEraser/RemarkableLamyEraser [[0;1;31m(code=exited, status=203/EXEC)[[0m
   Main PID: 708 (code=exited, status=203/EXEC)

Aug 11 08:13:43 reMarkable systemd[1]: LamyEraser.service: Scheduled restart job, restart counter is at 5.
Aug 11 08:13:43 reMarkable systemd[1]: Stopped Lamy Pen Button as Eraser.
Aug 11 08:13:43 reMarkable systemd[1]: [[0;1;38;5;185m[[0;1;39m[[0;1;38;5;185mLamyEraser.service: Start request repeated too quickly.[[0m
Aug 11 08:13:43 reMarkable systemd[1]: [[0;1;38;5;185m[[0;1;39m[[0;1;38;5;185mLamyEraser.service: Failed with result 'exit-code'.[[0m
Aug 11 08:13:43 reMarkable systemd[1]: [[0;1;31m[[0;1;39m[[0;1;31mFailed to start Lamy Pen Button as Eraser.[[0m

```

**Comment by h6y3** [comment]
FWIW, I am also on the beta program and it also doesn't work for me.  However, the old code is more or less sitting on the device so I just follow these instructions:  

https://github.com/isaacwisdom/RemarkableLamyEraser/blob/0b044b72349012dc0bb0922628fe1802e22d569b/README.md

Notably, I think at some  point LamyEraser.service was deleted - not sure if that was intentional, but without starting the service from the old builds it doesn't seem to work.

**Comment by isaacwisdom** [comment]
Ok! I think I might have solved the issue. A few commits ago, I made a change to where the executable is placed on the device, but I forgot to update this in the service file. I think installs should work now.

**Comment by WaylonWillie** [comment]
I'm installed and button erasing!!! (RM2, 2.14.1.866) Thanks for being so responsive, this is a great addition to the RM.
