### ISSUE TITLE
Eraser thickness

### ISSUE THREAD

**Issue by runty** [isaacwisdom/RemarkableLamyEraser#3]
Is there any way to increase the eraser thickness?

**Comment by isaacwisdom** [comment]
The eraser will follow the behavior of the Marker Plus Eraser, which has two thicknesses. Holding the pen upright will give you the large erasing diameter and holding it like you're writing will give you the small erasing diameter.

**Comment by isaacwisdom** [comment]
Unfortunately these thicknesses are controlled by xochitl, so they are outside the scope of this project.

**Comment by jansvrs** [comment]
Consider adding this to the readme. I was about to ask this and only discovered this closed discussion accidentally.
