### ISSUE TITLE
Lost functionality with 2.14.3.1005

### ISSUE THREAD

**Issue by WaylonWillie** [isaacwisdom/RemarkableLamyEraser#34]
Unfortunately I updated to 2.14.3.1005, and I am not getting this to work with a reinstall of the RemarkableLamyEraser tool (I tried v1 and v2). I'm on a stock RM2 with no other mods. All was working well before the update. Of course this could be something with my particular device, but I thought I'd drop a note here.

**Comment by smancuso** [comment]
I have the same version, and it is working for me.

**Comment by WaylonWillie** [comment]
Another user noted that this version was working for them. I tried again and it worked on the first try. Sorry for the disturbance!
