### ISSUE TITLE
A request: lazo tool personalization

### ISSUE THREAD

**Issue by Colo219** [isaacwisdom/RemarkableLamyEraser#39]
hello, this is a request not a proper issue. If it's possible it would be amazing if in the personalization options there was the possibility to choose (in toggle or in press) the possibility to use the lasso tool in order to select text without have to open the controls panel. 

Thank you for your work!

**Comment by isaacwisdom** [comment]
Hi - 
Try checking out the V2 branch, which I think has the features that you are looking for. Some features, such as the lasso tool, tend to be a little buggy, which is why I haven't made an official "upgrade" to the V2 branch.

**Comment by Colo219** [comment]
ok, thank you I will try it!
