### ISSUE TITLE
TLS certificate validation not implemented 

### ISSUE THREAD

**Issue by minguanyun** [isaacwisdom/RemarkableLamyEraser#41]
Hello, 

thanks for your resource. But when I put in the install code on SSH command board, it says "wget: note: TLS certificate validation not implemented". I don't know how to solve this question

**Comment by isaacwisdom** [comment]
That's a pretty normal message that comes from the way the wget command downloads the installer from github. It's a security message telling you that you're downloading from a source without using a valid certificate, which poses some security risks. However, it's just a warning and the download should proceed normally. Does your install hang?

**Comment by allyourcodearebelongtous** [comment]
This can be suppressed by adding --no-check-certificate to the wget command:
````
 sh -c "$(wget --no-check-certificate https://github.com/isaacwisdom/RemarkableLamyEraser/raw/v1/LamyInstall.sh -O-)"

This option has to be added in LamyInstaller.sh as well to remove the warning.
