### ISSUE TITLE
Support for other pens

### ISSUE THREAD

**Issue by arturbecker** [isaacwisdom/RemarkableLamyEraser#43]
Is this project potentially compatible with other pens that have one button and use Wacom EMR? e.g. https://www.staedtler.com/intl/en/products/pencils-and-accessories/stylus/noris-digital-jumbo-180j-22-stylus-pencil-180j-22-1/

**Comment by isaacwisdom** [comment]
From what I can see, that pen already has an eraser feature built in to it, similar to how the marker plus does, meaning that I think that pen should just erase "naturally," with no need for my tool (the [wiki](https://remarkablewiki.com/tech/stylus/staedtler-noris-digital-jumbo) seems to suggest the same.) Are you looking to use the extended functionality available with this tool?

**Comment by arturbecker** [comment]
Thanks Isaac! That sounds great. For context, I have the rm1, so I believe erasing with the built-in eraser will not work out of the box?

**Comment by isaacwisdom** [comment]
Gotcha. So the RM1 actually doesn't have support for the BTN_TOOL_RUBBER ev code that the marker plus and other EMR pens use for the eraser, meaning that the eraser on any of these pens is effectively invisible to the RM1 tablet, so it's impossible to do anything with it. 

Both tablets, however, do support the BTN_STYLUS event that is used for reading the button on many of these pens, and that's what I look for in my code to do things. However, it looks like the Noris jumbo doesn't have any button on it, meaning it can't send anything to the RM1 beyond pen movements.

**Comment by arturbecker** [comment]
Thanks again! I didn't realize the eraser and button were different things (I thought the eraser could count as a button), thanks for the clarification. Then a Lamy-like pen and your code seem to be the way to go!
