### ISSUE TITLE
"toolbar" option seems to select the bottom-left element instead after OS upgrade

### ISSUE THREAD

**Issue by javalasers** [isaacwisdom/RemarkableLamyEraser#45]
Just updated to 3.0.4.1305 [production release]. [Don't know if the upgrade is a red herring, but it's the only thing I know has changed].

Now when I do a single button click, instead of making the toolbar appear/disappear, it instead activates the button in the bottom-left of the UI (which lets you add a new page, search, access notebook settings, etc.).

My config looks like:

click                       toolbar
double-click
triple-click
quadruple-click
quintuple-click

press&hold                  eraser
double-press&hold
triple-press&hold
quadruple-press&hold
quintuple-press&hold

**Comment by isaacwisdom** [comment]
This is possibly the same as #44. What kind of document did you have open that was exhibiting this behavior? Also, it sounds like you are using a document in Right hand, portrait orientation?

**Comment by javalasers** [comment]
Right hand, portrait mode, yes. Was experiencing this in notebook (quick sheets, but appears to be all notebooks). Just checked, and same thing is happening in PDF as well.

I should have noted this originally but all of this is with the v2 branch installed as of a week or so ago. Thanks!

**Comment by javalasers** [comment]
Hmm, I just restarted the tablet via the settings menu, and now the toolbar functionality is back on click. Very odd. LMK if there are debugging signals you'd like me to gather if/when the problem recurs...

**Comment by isaacwisdom** [comment]
Sounds like the issue was resolved after your restart. The fix for the other issues in v is on its way
