### ISSUE TITLE
SSH - wget command not working anymore

### ISSUE THREAD

**Issue by Lars997** [isaacwisdom/RemarkableLamyEraser#48]
Thanks for your great extension, however, I eceive "bad addres "github.com" no such file or directory. 

Did something change on the link?

Thanks

**Comment by Lars997** [comment]
OK works now! - I answer the question myself. Maybe someone else has similar issues:

My remarkable was on "wifi off" - so obviously it wasnt able to resolve the hash-tag ;)

**Comment by Eeems** [comment]
@Lars997 it sounds like you can close this issue now?
