### ISSUE TITLE
Issues on v3 & rM1 (wrong or no function triggered)

### ISSUE THREAD

**Issue by hagenblix** [isaacwisdom/RemarkableLamyEraser#53]
On the rM1 with software version v3.3, there are similar issues to [issue 44](https://github.com/isaacwisdom/RemarkableLamyEraser/issues/44), with the default configuration of the version 2 script, where  _press & hold_ is configured with the _eraser_ function.

* In PDF mode, _press & hold_ selects the eraser, as intended, but does not go back to the pen mode when releasing. Also, it only does anything if the toolbar is open, otherwise there are no effects.
* In notebook mode, _press & hold_ instead triggers the printed text insertion feature (which is presumably in the same spot?)

Happy to provide debugging/testing help if there is something that can be done!

**Comment by alioth9** [comment]
rM1 with SW v3.3
I have the same problem/behaviour as hagenblix. It seams that RLE doesn't detect sw version for rM1 or since the test for bulding rM1 code is made on a pdf it didn't take into account the Text  tool that came with sw 3.+.

**Comment by alioth9** [comment]
In fact after further reading of the code (in particular sources/main.c)
and test with 
RemarkableLamyEraser --test-locations WACOM
it seems that for the rM1 it the touch dev that is used  but is buggy
With the test It appears the wacom work well (without the detection of orientation nor left hand: allways in Portrait Right hand mode) and triggers all the tools. So maybe detect the version of the SW (V3.+) and use fd_wacom in this case or ...

To test the wacom in the case of rM1 and v3.3+ maybe could you create a branch of v2-3.0.0-fix that use fd_wacom in place of fd_touch in main.c for the  rmVersion == 1

**Comment by isaacwisdom** [comment]
Some of the issues should be fixed as of [8b8f163](https://github.com/isaacwisdom/RemarkableLamyEraser/commit/8b8f163fd09586e789cdf72c161d2144247ebfa5). In particular, this should account for the new text tool in notebooks and its absence in PDFs. Try it out and let me know of any bugs you notice!
