### ISSUE TITLE
v3.5 beta seems to have caused some issues

### ISSUE THREAD

**Issue by AtheistP3ace** [isaacwisdom/RemarkableLamyEraser#55]
I believe the toolbar changes may have broken the screen mappings perhaps? Either way double click to undo no longer works. I tried using "writing" on click and that also did not work. Thanks!!

**Comment by k1sr** [comment]
I can confirm similar issues, including double press and hold does not enable select.

**Comment by isaacwisdom** [comment]
Some of the issues should be fixed as of [8b8f163](https://github.com/isaacwisdom/RemarkableLamyEraser/commit/8b8f163fd09586e789cdf72c161d2144247ebfa5). In particular, this should account for the new text tool in notebooks and its absence in PDFs. Try it out and let me know of any bugs you notice!
