### ISSUE TITLE
Only Erase working with default configuration on RM2 Version 3.3.2.1666

### ISSUE THREAD

**Issue by jafish** [isaacwisdom/RemarkableLamyEraser#58]
On my RM2, software 3.3.2.1666, using the Lamy, I'm seeing strange behavior with the console showing "writing select" for double-press&hold, but the actual behavior on the reMarkable is running the undo action. I'm using the default configuration, so "writing select" is triggered by double-press&hold. "writing undo" is what I see in the console when I double-click, but it does not do anything on the screen. The only action working properly according to my configuration is the press&hold for eraser-erase. 

### press&hold

```shell
writing eraser
Activating ToolEraserRM2: writing eraser on
writing eraser
Deactivating ToolEraserRM2: writing pen on
``` 

### double-press&hold

```shell
writing select

writing select

``` 

### double-click

```shell
writing undo

```

**Comment by isaacwisdom** [comment]
Hi! Can you please uninstall, and redownload from the [v2-3.0.0-fix](https://github.com/isaacwisdom/RemarkableLamyEraser/tree/v2-3.0.0-fix) branch?

**Comment by javalasers** [comment]
Also experiencing this, even after an uninstall/reinstall from v2-3.0.0-fix

**Comment by javalasers** [comment]
[And to be clear, my reMarkable 2 UI is showing the software version as 3.4.01784, but if I run RemarkableLamyEraser directly on the commandline it's showing the version as 3.3.2.1666; however, I believe this is due to a bug in the config-parsing logic, which I filed a separate issue for...

**Comment by k1sr** [comment]
I can confirm the same/similar issues on 3.5.1.1791 Beta.  v2-3.0.0-fix only work for pen-style erase. All other actions do nothing. However; if I run the service via console, it does report that these actions are being sent and received; however they are not doing anything on the RM2

**Comment by vancinad** [comment]
@jafish : How do you get that console display? I've got the same problem ("press and hold for erase" is the only function working) but don't know how to collect more diagnostic information.

**Comment by rachentp** [comment]
> @jafish : How do you get that console display? I've got the same problem ("press and hold for erase" is the only function working) but don't know how to collect more diagnostic information.

After opening terminal and connecting via ssh, stop Lamy service, then run command manually with, "RemarkableLamyEraser". Key presses should show up in terminal.

Just uninstalled and reinstalled from v2-3.0.0-fix. I cannot get any functions to work (from default configuration) except pen erase. Interestingly when I first un/reinstalled I got this output:
```
RemarkableLamyEraser 2.0.0
Detected ReMarkable 2, Software Version: 3.x.x.x
Using Devices:
1. device file = /dev/input/event1
   device name = Wacom I2C Digitizer
2. device file = /dev/input/event2
   device name = pt_mt
```
Now I have this:
```
RemarkableLamyEraser 2.0.0
Detected ReMarkable 2. Using Devices:
1. device file = /dev/input/event1
   device name = Wacom I2C Digitizer
2. device file = /dev/input/event2
   device name = pt_mt
```
The one with software version 3.x.x.x doesn't activate any tools, but the second one does. I at least get, "Activating ToolEraserRM2: writing eraser on" and "Deactivating ToolEraserRM2: writing pen on".

**Comment by isaacwisdom** [comment]
> > @jafish : How do you get that console display? I've got the same problem ("press and hold for erase" is the only function working) but don't know how to collect more diagnostic information.
> 
> After opening terminal and connecting via ssh, stop Lamy service, then run command manually with, "RemarkableLamyEraser". Key presses should show up in terminal.
> 
> Just uninstalled and reinstalled from v2-3.0.0-fix. I cannot get any functions to work (from default configuration) except pen erase. Interestingly when I first un/reinstalled I got this output:
> 
> ```
> RemarkableLamyEraser 2.0.0
> Detected ReMarkable 2, Software Version: 3.x.x.x
> Using Devices:
> 1. device file = /dev/input/event1
>    device name = Wacom I2C Digitizer
> 2. device file = /dev/input/event2
>    device name = pt_mt
> ```
> 
> Now I have this:
> 
> ```
> RemarkableLamyEraser 2.0.0
> Detected ReMarkable 2. Using Devices:
> 1. device file = /dev/input/event1
>    device name = Wacom I2C Digitizer
> 2. device file = /dev/input/event2
>    device name = pt_mt
> ```
> 
> The one with software version 3.x.x.x doesn't activate any tools, but the second one does. I at least get, "Activating ToolEraserRM2: writing eraser on" and "Deactivating ToolEraserRM2: writing pen on".
> 
> Edit: using Remarkable version 3.4.1.1790

Interesting. Can you `cd; ls -a` and look for a file called RemarkableLamyEraser in the output?

**Comment by rachentp** [comment]
I can't now, I already un/reinstalled your latest fixes, LOL. However, after doing that I have "Software Version: 3.x.x.x". Super interesting though, I just ran `cd; ls -a` and this is the output:
```
reMarkable: ~/ cd; ls -a
.                 .bash_history     .cache            .local            LamyUninstall.sh  log.txt.old
..                .bashrc           .config           .vimrc            log.txt
```

**Comment by seanlvjie** [comment]
the same,
3.4.1.1790, with v2-3.0.0.-fix

only press&hold eraser-erase works

**Comment by slotThe** [comment]
Should work in https://github.com/slotThe/RemarkableLamyEraser/ and thus also on the `main` branch (and at some point this repo will use that as its default branch!)
