### ISSUE TITLE
Download issue

### ISSUE THREAD

**Issue by Mrlwallace** [isaacwisdom/RemarkableLamyEraser#59]
I am having problems downloading the files. I am running RM2 version 3.1.4.1790
The errors are 
wget: note: TLS certificate validation not implemented

wget: server returned error: HTTP/1.1 404 Not Found

chmod: LamyInstall.sh: No such file or directory

-sh: /Lamyinstall.sh: No such file or directory

rm: can't remove '/home/root/LamyInstall.sh': No such file or directory

**Comment by isaacwisdom** [comment]
Can you verify your reMarkable's connection? The device needs an internet connection to download the files.

**Comment by Mrlwallace** [comment]
Yes, it is connected to my Wifi. That's how I am doing ssh.And I was able to add some other 3rd party templates.

Sent from Yahoo Mail on Android 
 
  On Sat, Jun 17, 2023 at 11:29 PM, Isaac ***@***.***> wrote:   


Can you verify your reMarkable's connection? The device needs an internet connection to download the files.

**Comment by isaacwisdom** [comment]
Ok. Can you confirm which branch you are using?

**Comment by Mrlwallace** [comment]
I was on the 2.0-3.0fix branch.

Sent from Yahoo Mail on Android 
 
  On Tue, Jun 20, 2023 at 6:54 PM, Isaac ***@***.***> wrote:   


Ok. Can you confirm which branch you are using?

**Comment by isaacwisdom** [comment]
Ok. I can't seem to find any place where there would be an error, and downloading and installing from the v2-3.0.0-fix branch works for me. Are you able to try again and report back? If it still doesn't work, go ahead and reopen the issue.
