### ISSUE TITLE
V. 3.5.1.1798 (Only Press&hold erase works)

### ISSUE THREAD

**Issue by Urbankey1993** [isaacwisdom/RemarkableLamyEraser#67]
When installing (using the FIX) the only part that works is the press&hold erase.
I tried to change the default to eraser-selection, but then it does not register anymore. 
Even the basic commands no longer work (undo and select). 

Here is my current config file. 

![image](https://github.com/isaacwisdom/RemarkableLamyEraser/assets/69200002/195eac80-4982-465f-a567-b3f2ecac8a70)

**Comment by Urbankey1993** [comment]
Going into the input display it shows:
![image](https://github.com/isaacwisdom/RemarkableLamyEraser/assets/69200002/737ec34c-963d-4fe9-9c23-9ca71d0aa40f)

**Comment by mikatachan** [comment]
I couldn't get the button to do anything other than erase also. Even though the input display shows that the command is working correctly, the remarkable 2 itself isn't following the command...

**Comment by mikatachan** [comment]
Update: Having updating to Version 3.5.2.1807, the hold-erase no longer works (actually no commands do). When I try to look at what it's doing, it seems to be inputting the commands correctly, but nothing is happening on the reMarkable 2.

![image](https://github.com/isaacwisdom/RemarkableLamyEraser/assets/117631871/49a7b08a-433f-4ae6-925a-58a2393d1c80)

**Comment by shortyjacobs** [comment]
Also on 3.5.2.1807 - hold-erase still works for me, no other commands do.  Not sure if this is always the case, but using the command readout as shown below lets me see when it works....pen nib needs to be ~1-2mm max above remarkable surface for button presses to register, maybe that's normal (I'm new!).

![image](https://github.com/isaacwisdom/RemarkableLamyEraser/assets/74113882/4105f681-8b7b-4fa2-9a5c-426d465be9ae)

**Comment by lowerzen1** [comment]
Trying to get the button to work for erase selection.  I lost all eraser button functionality when I accidentally updated to 3.5.2.1807 on my RM1.  I installed the Fix and I'm getting an error that states I'm running 2.15.1.1189 and need to be on 3.0.0.0 or newer.  I'm not sure where that's coming from, I wish I could actually go back to 2.12.1.1189 again! Does anyone know why it would say I am still on 2.15.1.1189?
