### ISSUE TITLE
Double press to undo sometimes doesn't work

### ISSUE THREAD

**Issue by isaacwisdom** [isaacwisdom/RemarkableLamyEraser#7]
Not really sure why, but in any case, I've noticed that lifting your hand off the screen and then placing it again will eventually make the double press to undo work. There might be a better way of writing the touch events in writeTapWithTouch to make the reMarkable handle the touch events better.

**Comment by isaacwisdom** [comment]
This same issue is appearing in the RM1 support, meaning this needs to be fixed.

**Comment by jansvrs** [comment]
Double press to undo only works for me when the nib is close enough to the tablet. I was gonna report this as a possible bug... but I guess it has to be close enough for the tablet to register the pen? Now that I think about it, it makes sense, and I don't know why I thought it could work when the pen is farther away than that. 😂

Thank you for making this 🙏really makes the Lamy pen SO good with the rM

**Comment by isaacwisdom** [comment]
Well it's been a long time since I opened this, and undoing has worked for me consistently for a long time now. I suppose this issue can be considered closed.
