### ISSUE TITLE
Doesn't work with Left-handed setup

### ISSUE THREAD

**Issue by dkoenigsberg** [isaacwisdom/RemarkableLamyEraser#74]
First of all, thanks for your hard work!

My problem: I've been trying each of the branches to no avail and then I decided to switch to right-handed mode and try it. Suddenly, the hack works!
How do I set it up to work left-handed?

**** FOLLOWUP EDIT ****
I just started to browse the code and I noticed the --left-handed argument that can be passed to the code. I didn't see that in the documentation on the main branch and stopped reading closely as I explored other branches.

If this helps anyone else, edit the LamyEraser.service file and add the --left-handed argument

**Comment by raju-bitter** [comment]
@isaacwisdom doesn't have the time to continue to support this projec, as far as I read. @slotThe has taken over, and he mentioned in a comment that left hand support needs to be added: https://github.com/isaacwisdom/RemarkableLamyEraser/issues/70#issuecomment-1712465808

Maybe you should create an issue here: https://github.com/slotThe/RemarkableLamyEraser
Can @isaacwisdom or @slotThe please comment on where we should create new issues? This repo, or here? https://github.com/slotThe/RemarkableLamyEraser

**Comment by slotThe** [comment]
> @isaacwisdom doesn't have the time to continue to support this projec, as far as I read. @slotThe has taken over, and he mentioned in a comment that left hand support needs to be added: [#70 (comment)](https://github.com/isaacwisdom/RemarkableLamyEraser/issues/70#issuecomment-1712465808)

Left hand support should work (at least, it did last time I checked!) in my fork.

> Maybe you should create an issue here: https://github.com/slotThe/RemarkableLamyEraser Can @isaacwisdom or @slotThe please comment on where we should create new issues? This repo, or here? https://github.com/slotThe/RemarkableLamyEraser

Currently in https://github.com/slotThe/RemarkableLamyEraser, though once I have enough rights I plan to upstream all of this here, set the main branch to `main`, and continue development in the main repo.
