### ISSUE TITLE
Undo action only works for right hand, portrait orientation

### ISSUE THREAD

**Issue by isaacwisdom** [isaacwisdom/RemarkableLamyEraser#8]
Good news, this can be fixed.

First, find the open document:
Finding the open document can be done by getting the PID of xochitl (ie. w/ `ps | grep xochitl`)
and then finding a *.lock file in /proc/<PID>/fd (ie. w/ `ls -l /proc/<PID>/fd | grep .lock`)
This .lock will start with a UUID (or atleast I think its a UUID) that looks something like 3ea1680e-2003-4581-80f5-e2afab4850b5.

Then, find the orientation of that document:
The orientation of a document "3ea1680e-2003-4581-80f5-e2afab4850b5" can be found in here: ~/.local/share/remarkable/xochitl/3ea1680e-2003-4581-80f5-e2afab4850b5.content

ie, running `cat ~/.local/share/remarkable/xochitl/3ea1680e-2003-4581-80f5-e2afab4850b5.content | grep orientation`
returns `"orientation": "portrait",` or `"orientation": "landscape",`

I just have to figure out how to implement these in C instead of as shell commands, and then make some functions like getOpenDoc() and getOrientation() that can be called every time the undo action is performed, to determine which specific undo sequence needs to be performed.

I still need to work out how to tell what orientation the tablet is in. I'm sure there's a file somewhere that can be checked for whether the tablet is in right-hand or left-hand orientation.

**Comment by isaacwisdom** [comment]
Alright, the right hand vs left hand orientation can be found in ~/.config/remarkable/xochitl.conf. Running `cat ~/.config/remarkable/xochitl.conf | grep RightHanded` returns `RightHanded=true` or `RightHanded=false`

**Comment by Toorero** [comment]
If you just want to use the shell commands, you could use popen and pclose I would guess.

**Comment by isaacwisdom** [comment]
Here's a command that outputs the GUID of the currently open notebook.  
PID=`pidof xochitl`; ls -l /proc/$PID/fd | grep .lock  | sed 's/.*\///' | sed 's/\..*//'

**Comment by isaacwisdom** [comment]
Above command updated to be a bit more specific on only returning the UUID, and cleaner to read (no sed).

<pre> PID=`pidof xochitl`; ls -l /proc/$PID/fd | grep lock | egrep -v 'rm|xochitl/xochitl' | egrep '[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{8}' -o </pre>

**Comment by isaacwisdom** [comment]
Alright, another update to the command. Redirect stderr of ls to /dev/null it doesn't appear in the output. ls sometimes throws some errors when working with the /proc/ folder.
<pre>PID=`pidof xochitl`; ls -l /proc/$PID/fd 2> /dev/null | grep lock | egrep -v 'rm|xochitl/xochitl' | egrep '[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{8}' -o</pre>

**Comment by isaacwisdom** [comment]
Another problem with that command :/
The guid has blocks of 8,4,4,4,12, not 8,4,4,4,8 as the command above uses. Corrected:
<pre>PID=`pidof xochitl`; ls -l /proc/$PID/fd 2> /dev/null | grep lock | egrep -v 'rm|xochitl/xochitl' | egrep '[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12}' -o</pre>
